import { Plugin } from 'vite';
import * as fs from 'fs';
import * as path from 'path';

interface FileItem {
  type: 'file';
  name: string;
  size: string;
  url: string;
}

interface FolderItem {
  type: 'folder';
  name: string;
  children: FileSystemItem[];
}

type FileSystemItem = FileItem | FolderItem;

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function scanDirectory(dirPath: string, baseUrl: string): FileSystemItem[] {
  const items: FileSystemItem[] = [];
  
  if (!fs.existsSync(dirPath)) {
    return items;
  }

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    const relativePath = path.join(baseUrl, entry.name).replace(/\\/g, '/');

    if (entry.isDirectory()) {
      items.push({
        type: 'folder',
        name: entry.name,
        children: scanDirectory(fullPath, relativePath),
      });
    } else if (entry.isFile()) {
      const stats = fs.statSync(fullPath);
      items.push({
        type: 'file',
        name: entry.name,
        size: formatFileSize(stats.size),
        url: '/' + relativePath,
      });
    }
  }

  // Sort: folders first, then files, both alphabetically
  return items.sort((a, b) => {
    if (a.type !== b.type) return a.type === 'folder' ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
}

export function fileSystemScanner(options: { sourceDir?: string } = {}): Plugin {
  const sourceDir = options.sourceDir || 'public/files';

  return {
    name: 'file-system-scanner',
    buildStart() {
      generateFileSystem(sourceDir);
    },
    configureServer(server) {
      // Watch for changes in dev mode
      const watchPath = path.resolve(process.cwd(), sourceDir);
      
      if (fs.existsSync(watchPath)) {
        server.watcher.add(watchPath);
        server.watcher.on('all', (event, changedPath) => {
          if (changedPath.startsWith(watchPath)) {
            generateFileSystem(sourceDir);
          }
        });
      }
      
      // Generate on server start
      generateFileSystem(sourceDir);
    },
  };
}

function generateFileSystem(sourceDir: string) {
  const absolutePath = path.resolve(process.cwd(), sourceDir);
  const outputPath = path.resolve(process.cwd(), 'src/data/fileSystem.generated.ts');
  
  const fileSystem = scanDirectory(absolutePath, 'files');
  
  const content = `// Auto-generated by fileSystemScanner plugin
// Do not edit manually - changes will be overwritten
// Add files to the "${sourceDir}" folder and rebuild

import type { FileSystemItem } from '@/types/files';

export const fileSystem: FileSystemItem[] = ${JSON.stringify(fileSystem, null, 2)};
`;

  // Ensure directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`[file-system-scanner] Generated file system from ${sourceDir}`);
}
