// Auto-generated by fileSystemScanner plugin
// Do not edit manually - changes will be overwritten
// Add files to the "public/files" folder and rebuild

import type { FileSystemItem } from '@/types/files';

export const fileSystem: FileSystemItem[] = [];
